---
# tasks file for sql-database

# This playbook is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


- name: SQL database
  yum: name={{ item }} state=present
  with_items:
    - "mariadb"
    - "mariadb-server"
    - "MySQL-python"
  notify:
    - restart mariadb service

- name: config file
  ini_file: dest=/etc/my.cnf.d/mariadb_openstack.cnf section=mysqld option={{ item.key }} value={{ item.value }}
  with_dict:
    "bind-address": "{{ controller_management_ip }}"
    "default-storage-engine": innodb
    "collation-server": utf8_general_ci
    "init-connect": 'SET NAMES utf8'
    "character-set-server": utf8
  notify:
    - restart mariadb service

- meta: flush_handlers

# http://stackoverflow.com/questions/16444306/ansible-idempotent-mysql-installation-playbook

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: Change root user password on first run
  mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      priv: "*.*:ALL,GRANT"
      host: "{{ item }}"
  with_items:
    - "{{ controller_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: delete anonymous MySQL server user for {{ ansible_hostname }}
  mysql_user: login_user=root login_password={{ mysql_root_password }} user="" host="{{ ansible_hostname }}" state="absent"

- name: delete anonymous MySQL server user for localhost
  mysql_user: login_user=root login_password={{ mysql_root_password }} user="" state="absent"

- name: remove the MySQL test database
  mysql_db: login_user=root login_password={{ mysql_root_password }} db=test state=absent
