---
# tasks file for neutron-compute

# This playbook is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.



- name: configure public interface
  lineinfile:
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ public_interface_name }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: "{{ item.state }}"
  with_items:
      - regexp: "^TYPE"
        line: TYPE=Ethernet
        state: present
      - regexp: "^BOOTPROTO"
        line: 'BOOTPROTO="none"'
        state: present
      - regexp: "^IPADDR"
        line: ""
        state: absent
      - regexp: "^NETMASK"
        line: ""
        state: absent
      - regexp: "^PEERDNS"
        line: ""
        state: absent
  notify:
    - restart the network.service

- meta: flush_handlers

- name: Packages
  yum: name={{ item }} state=present
  with_items:
    - openstack-neutron
    - openstack-neutron-linuxbridge
    - ebtables
    - ipset

- name: configuration
  ini_file:
      dest: /etc/neutron/neutron.conf
      section: "{{ item.s }}"
      option: "{{ item.k }}"
      value: "{{ item.v }}"
  with_items:
    - s: DEFAULT
      k: rpc_backend
      v: rabbit
    - s: oslo_messaging_rabbit
      k: rabbit_host
      v: "{{ controller_hostname }}"
    - s: oslo_messaging_rabbit
      k: rabbit_userid
      v: openstack
    - s: oslo_messaging_rabbit
      k: rabbit_password
      v: "{{ rabbit_password }}"
    - s: DEFAULT
      k: auth_strategy
      v: keystone
    - s: DEFAULT
      k: auth_strategy
      v: keystone
    - s: keystone_authtoken
      k: auth_uri
      v: http://{{ controller_hostname }}:5000
    - s: keystone_authtoken
      k: auth_url
      v: http://{{ controller_hostname }}:35357
    - s: keystone_authtoken
      k: auth_plugin
      v: password
    - s: keystone_authtoken
      k: project_domain_id
      v: default
    - s: keystone_authtoken
      k: user_domain_id
      v: default
    - s: keystone_authtoken
      k: project_name
      v: service
    - s: keystone_authtoken
      k: username
      v: neutron
    - s: keystone_authtoken
      k: password
      v: "{{ neutron_password }}"
    - s: oslo_concurrency
      k: lock_path
      v: /var/lib/neutron/tmp
    - s: DEFAULT
      k: verbose
      v: "True"
  notify:
    - restart and enable network services

- name: configuration of the linux bridge agent
  ini_file:
      dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      section: "{{ item.s }}"
      option: "{{ item.k }}"
      value: "{{ item.v }}"
  with_items:
    - s: linux_bridge
      k: physical_interface_mappings
      v: public:{{ public_interface_name }}
    - s: vxlan
      k: enable_vxlan
      v: "True"
    - s: vxlan
      k: local_ip
      v: "{{ overlay_interface_ip }}"
    - s: vxlan
      k: l2_population
      v: "True"
    - s: agent
      k: prevent_arp_spoofing
      v: "True"
    - s: securitygroup
      k: enable_security_group
      v: "True"
    - s: securitygroup
      k: firewall_driver
      v: neutron.agent.linux.iptables_firewall.IptablesFirewallDriver
  notify:
    - restart and enable network services

- name: configuration of Nova to use Networking
  ini_file:
      dest: /etc/nova/nova.conf
      section: "{{ item.s }}"
      option: "{{ item.k }}"
      value: "{{ item.v }}"
  with_items:
    - s: neutron
      k: url
      v: http://{{ controller_hostname }}:9696
    - s: neutron
      k: auth_url
      v: http://{{ controller_hostname }}:35357
    - s: neutron
      k: auth_plugin
      v: password
    - s: neutron
      k: project_domain_id
      v: default
    - s: neutron
      k: user_domain_id
      v: default
    - s: neutron
      k: project_name
      v: service
    - s: neutron
      k: username
      v: neutron
    - s: neutron
      k: password
      v: "{{ neutron_password }}"
  notify:
    - restart and enable network services

- meta: flush_handlers
