---
# tasks file for cinder-storage
- name: Packages
  yum: name={{ item }} state=present
  with_items:
    - lvm2
    - openstack-cinder
    - targetcli
    - python-oslo-policy
  notify:
    - restart lvm2 metadata service

- name: create lvm physical volume and volume group
  lvg: vg={{ cinder_volume_group }} pvs={{ cinder_partition }}


- name: configuration
  ini_file:
      dest: /etc/cinder/cinder.conf
      section: "{{ item.section }}"
      option: "{{ item.key }}"
      value: "{{ item.value }}"
  with_items:
      - section: database
        key: connection
        value: mysql://cinder:{{ cinder_db_password }}@{{ controller_hostname }}/cinder
      - section: DEFAULT
        key: rpc_backend
        value: rabbit
      - section: oslo_messaging_rabbit
        key: rabbit_host
        value: "{{ controller_hostname }}"
      - section: oslo_messaging_rabbit
        key: rabbit_userid
        value: openstack
      - section: oslo_messaging_rabbit
        key: rabbit_password
        value: "{{ rabbit_password }}"
      - section: DEFAULT
        key: auth_strategy
        value: keystone
      - section: keystone_authtoken
        key: auth_uri
        value: http://{{ controller_hostname }}:5000
      - section: keystone_authtoken
        key: auth_url
        value: http://{{ controller_hostname }}:35357
      - section: keystone_authtoken
        key: auth_plugin
        value: password
      - section: keystone_authtoken
        key: project_domain_id
        value: default
      - section: keystone_authtoken
        key: user_domain_id
        value: default
      - section: keystone_authtoken
        key: project_name
        value: service
      - section: keystone_authtoken
        key: username
        value: cinder
      - section: keystone_authtoken
        key: password
        value: "{{ cinder_password }}"
      - section: DEFAULT
        key: my_ip
        value: "{{ management_ip }}"
      - section: lvm
        key: volume_driver
        value: cinder.volume.drivers.lvm.LVMVolumeDriver
      - section: lvm
        key: volume_group
        value: "{{ cinder_volume_group }}"
      - section: lvm
        key: iscsi_protocol
        value: iscsi
      - section: lvm
        key: iscsi_helper
        value: lioadm
      - section: DEFAULT
        key: enabled_backends
        value: lvm
      - section: DEFAULT
        key: glance_host
        value: "{{ controller_hostname }}"
      - section: oslo_concurrency
        key: lock_path
        value: /var/lib/cinder/tmp
      - section: DEFAULT
        key: verbose
        value: "True"
  notify:
    - restart cinder volume services
